### PR TITLE
Link and Image Support

### PR DESCRIPTION
**Pull request by ralphschindler**
Support for issue #8

### CODE REVIEW

**Comment by divyanshu707** [comment]
@ralphschindler Thank you for this PR. Can you suggest a way to embed local images in markdown instead of hosted images?

**Comment by ralphschindler** [comment]
@divyanshu707 Hi! I don't believe I fully understand your question.  This PR allows for simple insertion and removal of link in the body markdown.  The path to the image, whether remote or local, should be completely supported.

**Comment by divyanshu707** [comment]
@ralphschindler I was talking about image upload support like [this](https://github.com/inacho/bootstrap-markdown-editor#implementing-the-image-upload) editor does. Sometimes end users want to embed local images and don't want to write the whole image path. They prefer uploading the image from their system.

**Comment by ralphschindler** [comment]
@divyanshu707 I believe that is outside the scope of this component and this PR. That said, it would be @JedWatson's call.

**Comment by elimisteve** [comment]
If we can already display images using markdown, then we can embed them by base64 encoding them, like this:

`red dot`

Rendered result: red dot

**Comment by elimisteve** [comment]
For anyone else who would like to try this `link-and-image` branch from npm, check out https://www.npmjs.com/package/react-md-editor-linkandimage

**Comment by elimisteve** [comment]
@ralphschindler This looks fantastic and I _really_ want to enable my users to add links and images to their markdown documents, but when I use this branch I don't see the additional buttons in the UI. I triple-checked and I am using this code. Am I doing something wrong, or is there something special I need to do to get the 2 extra buttons to show up? Thanks!

**Comment by elimisteve** [comment]
I now see that, for example, `src/format.js` has been updated, but `lib/format.js` and `dist/react-md-editor.js` haven't been. I've tried changing those files locally, but still can't get the link and image buttons to show up :-\. Any pointers would be appreciated! Gracias.

**Comment by elimisteve** [comment]
Got it, and sent @ralphschindler a PR: https://github.com/ralphschindler/react-md-editor/pull/1

**Comment by elimisteve** [comment]
Unfortunately the link and image support is buggy :-(. There are off-by-1 and off-by-N errors in the code that governs which characters are highlighted once you click the link or image buttons.

@ralphschindler Do you see the same behavior?

**Comment by ralphschindler** [comment]
@JedWatson is this PR something you're interested in?

@elimisteve I did not build the package as to keep my PR to @JedWatson clean, if he doesn't merge the PR or decides he doesn't want to continue the project, I would consider hosting a forked version of this repo for yourself.  I am actually not using node related projects much these days anymore.  I'll give this a few more days before I decide what to do with my fork.

**Comment by bf** [comment]
@JedWatson can you please decide on mergin this or not?

**Pull request closed without merging**
